# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DusTBALL
email: webmaster@dustball.tk
description: >
  Do what the fuck yoU wanT But don'T BlAme the author pubLic License
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dustball.tk" # the base hostname & protocol for your site
paginate:	1 # The number of posts to show per page on your homepage

name: 'Eibo Richter'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: ""
twitter_username: ""
github_username:  ""

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
